# Working with parquet files

## Objective

+ In this assignment, we will use the data downloaded with the module `data_manager` to create features.

(11 pts total)

## Prerequisites

+ This notebook assumes that price data is available to you in the environment variable `PRICE_DATA`. If you have not done so, then execute the notebook `01_materials/labs/2_data_engineering.ipynb` to create this data set.

+ Load the environment variables using dotenv. (1 pt)

In [12]:
%load_ext dotenv
%dotenv

The dotenv extension is already loaded. To reload it, use:
  %reload_ext dotenv

In [13]:
!pip install python-dotenv
!pip install dask

Requirement already satisfied: python-dotenv in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (1.1.1)
Requirement already satisfied: dask in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (2024.8.0)
Requirement already satisfied: click>=8.1 in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from dask) (8.1.8)
Requirement already satisfied: cloudpickle>=1.5.0 in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from dask) (3.1.1)
Requirement already satisfied: fsspec>=2021.09.0 in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from dask) (2025.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from dask) (25.0)
Requirement already satisfied: partd>=1.4.0 in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from dask) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from dask) (6.0.3)
Requirement already satisfied: toolz>=0.10.0 in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from dask) (1.0.0)
Requirement already satisfied: importlib-metadata>=4.13.0 in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from dask) (8.7.0)
Requirement already satisfied: colorama in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from click>=8.1->dask) (0.4.6)
Requirement already satisfied: zipp>=3.20 in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from importlib-metadata>=4.13.0->dask) (3.23.0)
Requirement already satisfied: locket in c:\users\kyuhw\miniconda3\envs\dsi_participant\lib\site-packages (from partd>=1.4.0->dask) (1.0.0)

In [22]:
import dask.dataframe as dd

+ Load the environment variable `PRICE_DATA`.
+ Use [glob](https://docs.python.org/3/library/glob.html) to find the path of all parquet files in the directory `PRICE_DATA`.

(1pt)

In [21]:
import os
from glob import glob

print(os.getenv("PRICE_DATA"))

#get the PRICE_DATA directory from env variable
PRICE_DATA = os.getenv("PRICE_DATA")

#find all parquet files inside the directory (../../05_src/data/prices/)
parquet_files = glob(os.path.join(PRICE_DATA, "**/*.parquet"), recursive = True) #by making recursive=True, we can go different layers of file systems

print(parquet_files)

../../05_src/data/prices/

For each ticker and using Dask, do the following:

+ Add lags for variables Close and Adj_Close.
+ Add returns based on Close:
    
    - `returns`: (Close / Close_lag_1) - 1

+ Add the following range: 

    - `hi_lo_range`: this is the day's High minus Low.

+ Assign the result to `dd_feat`.

(4 pt)

In [77]:
#1) Read all parquet files with Dask ; Result is a Dask DataFrame with ticker column as the index
dd_px = dd.read_parquet(parquet_files, engine="pyarrow").set_index("ticker")

#check this Dask dataframe 
dd_px.info()

#check which datatype 'Date' column is
dd_px["Date"].dtype #result is: <M8[ns] ; which is datetime64[ns]

dd_px.head()

<class 'dask.dataframe.core.DataFrame'>
Columns: 9 entries, Date to Year
dtypes: datetime64[ns](1), float64(6), int32(1), string(1)

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year
ticker,,,,,,,,,
ACN,2017-01-03,117.379997,117.809998,115.820000,116.459999,110.311638,2351600.0,ACN.csv,2017
ACN,2017-01-04,116.910004,117.800003,116.430000,116.739998,110.576851,2639800.0,ACN.csv,2017
ACN,2017-01-05,116.980003,117.139999,114.949997,114.989998,108.919258,3685400.0,ACN.csv,2017
ACN,2017-01-06,114.989998,116.739998,114.339996,116.300003,110.160088,4125300.0,ACN.csv,2017
ACN,2017-01-09,116.139999,116.349998,114.919998,115.000000,108.928719,2550800.0,ACN.csv,2017

In [78]:
dd_shift = dd_px.groupby('ticker', group_keys=False).apply(
    lambda x: x.assign(Close_lag_1 = x['Close'].shift(1),
    Adj_Close_lag_1 = x['Adj Close'].shift(1))
)

C:\Users\kyuhw\AppData\Local\Temp\ipykernel_14720\1574691086.py:1: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  dd_shift = dd_px.groupby('ticker', group_keys=False).apply(

In [79]:
dd_rets = dd_shift.assign(
    Returns = lambda x: x['Close']/x['Close_lag_1'] - 1,
    Adj_Returns = lambda y: y['Adj Close']/y['Adj_Close_lag_1'] - 1,
    hi_lo_range = lambda z: z['High'] - z['Low']
)

+ Convert the Dask data frame to a pandas data frame. 
+ Add a new feature containing the moving average of `returns` using a window of 10 days. There are several ways to solve this task, a simple one uses `.rolling(10).mean()`.

(3 pt)

In [107]:
"""
Dask is a lazy execution framework: commands will not execute until they are required. 
To trigger an execution in dask use `.compute()` -> this also saves to Pandas dataframe
"""
dd_rets.compute()

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Adj_Close_lag_1,Returns,Adj_Returns,hi_lo_range
ticker,,,,,,,,,,,,,,
ACN,2017-01-03,117.379997,117.809998,115.820000,116.459999,110.311638,2351600.0,ACN.csv,2017,NaN,NaN,NaN,NaN,1.989998
ACN,2017-01-04,116.910004,117.800003,116.430000,116.739998,110.576851,2639800.0,ACN.csv,2017,116.459999,110.311638,0.002404,0.002404,1.370003
ACN,2017-01-05,116.980003,117.139999,114.949997,114.989998,108.919258,3685400.0,ACN.csv,2017,116.739998,110.576851,-0.014991,-0.014990,2.190002
ACN,2017-01-06,114.989998,116.739998,114.339996,116.300003,110.160088,4125300.0,ACN.csv,2017,114.989998,108.919258,0.011392,0.011392,2.400002
ACN,2017-01-09,116.139999,116.349998,114.919998,115.000000,108.928719,2550800.0,ACN.csv,2017,116.300003,110.160088,-0.011178,-0.011178,1.430000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZIXI,2020-03-26,4.060000,4.530000,3.880000,4.510000,4.510000,1668500.0,ZIXI.csv,2020,4.000000,4.000000,0.127500,0.127500,0.650000
ZIXI,2020-03-27,4.490000,4.710000,4.100000,4.600000,4.600000,1146800.0,ZIXI.csv,2020,4.510000,4.510000,0.019956,0.019956,0.610000
ZIXI,2020-03-30,4.830000,4.870000,4.440000,4.640000,4.640000,1212000.0,ZIXI.csv,2020,4.600000,4.600000,0.008696,0.008696,0.430000
ZIXI,2020-03-31,4.600000,4.690000,4.100000,4.310000,4.310000,1057200.0,ZIXI.csv,2020,4.640000,4.640000,-0.071121,-0.071121,0.590000
ZIXI,2020-04-01,4.110000,4.160000,3.800000,3.820000,3.820000,539500.0,ZIXI.csv,2020,4.310000,4.310000,-0.113689,-0.113689,0.360000

In [108]:
dd_rets["returns_ma10"] = (
    dd_rets.groupby("ticker")["Returns"]
           .transform(lambda x: x.rolling(10).mean())
)

C:\Users\kyuhw\AppData\Local\Temp\ipykernel_14720\3888428571.py:2: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .transform(func)
  After:  .transform(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .transform(func, meta=('x', 'f8'))            for series result
  dd_rets.groupby("ticker")["Returns"]

In [109]:
dd_rets.head(30)

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Adj_Close_lag_1,Returns,Adj_Returns,hi_lo_range,returns_ma10
ticker,,,,,,,,,,,,,,,
ACN,2017-01-03,117.379997,117.809998,115.820000,116.459999,110.311638,2351600.0,ACN.csv,2017,NaN,NaN,NaN,NaN,1.989998,NaN
ACN,2017-01-04,116.910004,117.800003,116.430000,116.739998,110.576851,2639800.0,ACN.csv,2017,116.459999,110.311638,0.002404,0.002404,1.370003,NaN
ACN,2017-01-05,116.980003,117.139999,114.949997,114.989998,108.919258,3685400.0,ACN.csv,2017,116.739998,110.576851,-0.014991,-0.014990,2.190002,NaN
ACN,2017-01-06,114.989998,116.739998,114.339996,116.300003,110.160088,4125300.0,ACN.csv,2017,114.989998,108.919258,0.011392,0.011392,2.400002,NaN
ACN,2017-01-09,116.139999,116.349998,114.919998,115.000000,108.928719,2550800.0,ACN.csv,2017,116.300003,110.160088,-0.011178,-0.011178,1.430000,NaN
ACN,2017-01-10,114.940002,115.989998,114.639999,115.059998,108.985558,2550100.0,ACN.csv,2017,115.000000,108.928719,0.000522,0.000522,1.349998,NaN
ACN,2017-01-11,115.400002,116.260002,114.910004,116.120003,109.989594,2845800.0,ACN.csv,2017,115.059998,108.985558,0.009213,0.009213,1.349998,NaN
ACN,2017-01-12,115.620003,115.970001,114.839996,115.779999,109.667542,2110800.0,ACN.csv,2017,116.120003,109.989594,-0.002928,-0.002928,1.130005,NaN
ACN,2017-01-13,115.349998,117.440002,115.349998,116.949997,110.775764,2665600.0,ACN.csv,2017,115.779999,109.667542,0.010105,0.010105,2.090004,NaN
ACN,2017-01-17,115.919998,116.360001,115.470001,116.029999,109.904343,2374300.0,ACN.csv,2017,116.949997,110.775764,-0.007867,-0.007867,0.889999,NaN
ACN,2017-01-18,116.540001,116.949997,115.739998,115.949997,109.828568,2262200.0,ACN.csv,2017,116.029999,109.904343,-0.000689,-0.000689,1.209999,-0.000402
ACN,2017-01-19,115.599998,116.000000,115.269997,115.500000,109.402313,1647100.0,ACN.csv,2017,115.949997,109.828568,-0.003881,-0.003881,0.730003,-0.001030
ACN,2017-01-20,115.879997,116.250000,114.809998,115.070000,108.995018,2781400.0,ACN.csv,2017,115.500000,109.402313,-0.003723,-0.003723,1.440002,0.000097
ACN,2017-01-23,114.779999,115.269997,114.610001,114.820000,108.758224,2320000.0,ACN.csv,2017,115.070000,108.995018,-0.002173,-0.002173,0.659996,-0.001260
ACN,2017-01-24,115.199997,116.639999,114.839996,116.480003,110.330582,2810100.0,ACN.csv,2017,114.820000,108.758224,0.014457,0.014457,1.800003,0.001304
ACN,2017-01-25,116.900002,118.360001,116.699997,117.570000,111.363045,2905900.0,ACN.csv,2017,116.480003,110.330582,0.009358,0.009358,1.660004,0.002187
ACN,2017-01-26,116.989998,117.440002,115.620003,115.930000,109.809631,2864600.0,ACN.csv,2017,117.570000,111.363045,-0.013949,-0.013949,1.820000,-0.000129
ACN,2017-01-27,116.199997,116.440002,115.070000,115.349998,109.260246,2545100.0,ACN.csv,2017,115.930000,109.809631,-0.005003,-0.005003,1.370003,-0.000336
ACN,2017-01-30,115.320000,115.330002,113.410004,114.629997,108.578247,2529700.0,ACN.csv,2017,115.349998,109.260246,-0.006242,-0.006242,1.919998,-0.001971
ACN,2017-01-31,113.970001,114.019997,112.610001,113.870003,107.858383,2339000.0,ACN.csv,2017,114.629997,108.578247,-0.006630,-0.006630,1.409996,-0.001847
ACN,2017-02-01,113.800003,114.769997,112.309998,113.209999,107.233223,2471600.0,ACN.csv,2017,113.870003,107.858383,-0.005796,-0.005796,2.459999,-0.002358
ACN,2017-02-02,113.150002,113.769997,112.709999,113.639999,107.640526,2450500.0,ACN.csv,2017,113.209999,107.233223,0.003798,0.003798,1.059998,-0.001590
ACN,2017-02-03,114.000000,114.830002,113.339996,114.489998,108.445633,1663700.0,ACN.csv,2017,113.639999,107.640526,0.007480,0.007480,1.490005,-0.000470
ACN,2017-02-06,114.070000,115.220001,113.379997,114.180000,108.152016,2019400.0,ACN.csv,2017,114.489998,108.445633,-0.002708,-0.002708,1.840004,-0.000523
ACN,2017-02-07,114.949997,116.169998,114.949997,115.919998,109.800140,2538200.0,ACN.csv,2017,114.180000,108.152016,0.015239,0.015239,1.220001,-0.000445
ACN,2017-02-08,116.150002,116.150002,114.919998,115.430000,109.336014,2373700.0,ACN.csv,2017,115.919998,109.800140,-0.004227,-0.004227,1.230003,-0.001804
ACN,2017-02-09,115.430000,117.459999,115.430000,116.980003,110.804192,2117100.0,ACN.csv,2017,115.430000,109.336014,0.013428,0.013428,2.029999,0.000934
ACN,2017-02-10,116.699997,118.839996,116.519997,117.599998,111.391457,2183000.0,ACN.csv,2017,116.980003,110.804192,0.005300,0.005300,2.320000,0.001964
ACN,2017-02-13,117.900002,118.949997,117.730003,118.589996,112.329178,1988400.0,ACN.csv,2017,117.599998,111.391457,0.008418,0.008418,1.219994,0.003430
ACN,2017-02-14,118.470001,120.000000,118.410004,120.000000,113.664742,2559400.0,ACN.csv,2017,118.589996,112.329178,0.011890,0.011890,1.589996,0.005282

Please comment:

+ Was it necessary to convert to pandas to calculate the moving average return?
+ Would it have been better to do it in Dask? Why?

(1 pt)

For that question, we could have done in both Dask or Pandas Dataframe formats; not necessary. It would have been better with Dask since it is a package that enables parallel computing. And, since we originally had it in Dask dataframe format, it would have been better to have done all the necessary calculations within Dask df prior to converting to Pandas.

## Criteria

The [rubric](./assignment_1_rubric_clean.xlsx) contains the criteria for grading.

## Submission Information

🚨 **Please review our [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md)** 🚨 for detailed instructions on how to format, branch, and submit your work. Following these guidelines is crucial for your submissions to be evaluated correctly.

### Submission Parameters:
* Submission Due Date: `HH:MM AM/PM - DD/MM/YYYY`
* The branch name for your repo should be: `assignment-1`
* What to submit for this assignment:
    * This Jupyter Notebook (assignment_1.ipynb) should be populated and should be the only change in your pull request.
* What the pull request link should look like for this assignment: `https://github.com/<your_github_username>/production/pull/<pr_id>`
    * Open a private window in your browser. Copy and paste the link to your pull request into the address bar. Make sure you can see your pull request properly. This helps the technical facilitator and learning support staff review your submission easily.

Checklist:
- [ ] Created a branch with the correct naming convention.
- [ ] Ensured that the repository is public.
- [ ] Reviewed the PR description guidelines and adhered to them.
- [ ] Verify that the link is accessible in a private browser window.

If you encounter any difficulties or have questions, please don't hesitate to reach out to our team via our Slack at `#cohort-3-help`. Our Technical Facilitators and Learning Support staff are here to help you navigate any challenges.